spring:
  profiles:
    active: local
  mvc:
    path match:
      matching-strategy: ant_path_matcher
  jpa:
    show_sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true

