spring:
  datasource:
    url: ${url}
    username: ${username}
    password: ${password}
    driver-class-name: org.mariadb.jdbc.Driver
oauth:
  kakao:
    client-id: ${kakao-client-id}
    client-secret: ${kakao-client-secret}
    app-admin-key: ${kakao-app-admin-key}
    url:
      auth: https://kauth.kakao.com
      api: https://kapi.kakao.com
  google:
    client-id: ${google-client-id}
    client-secret: ${google-client-secret}
    url:
      auth: https://oauth2.googleapis.com
      api: https://www.googleapis.com

cloud:
  aws:
    credentials:
      accessKey: ${aws-access-key-id}
      secretKey: ${aws-secret-access-key}
    s3:
      bucket: mara-s3bucket
      dir: upload/
    region:
      static: ${aws-region}
#    stack:
#      auto: false

jwt:
  secret-key: ${jwt-secret-key}
  access-duration-mils: 2147483647

logging:
  level:
    root: info
    mara.server: TRACE