name: CI-CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - HOTFIX**

env:
  S3_BUCKET_NAME: mara-s3bucket
  AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
  AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
  AWS_REGION: ${{secrets.AWS_REGION}}
  RESOURCE_PATH: ./src/main/resources/application-dev.yml
  CODE_DEPLOY_APPLICATION_NAME: mara-code-deploy
  CODE_DEPLOY_DEPLOYMENT_GROUP_NAME: mara-deploy-group

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

        # [1]
      - name: Set yml file
        uses: microsoft/variable-substitution@v1
        with:
          files: ${{ env.RESOURCE_PATH }}
        env:
          spring.datasource.url: ${{ secrets.DB_URL }}
          spring.datasource.username: ${{ secrets.DB_USERNAME }}
          spring.datasource.password: ${{ secrets.DB_PASSWORD }}
          oauth.kakao.client-id: ${{ secrets.KAKAO_CLIENT_ID }}
          oauth.kakao.client-secret: ${{ secrets.KAKAO_CLIENT_SECRET}}
          oauth.kakao.app-admin-key: ${{ secrets.KAKAO_APP_ADMIN_KEY }}
          oauth.google.client-id: ${{ secrets.GOOGLE_CLIENT_ID }}
          oauth.google.client-secret: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          jwt.secret-key: ${{ secrets.JWT_SECRET_KEY }}
          cloud.aws.credentials.accessKey: ${{secrets.AWS_ACCESS_KEY_ID}}
          cloud.aws.credentials.secretKey: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          cloud.aws.region.static: ${{secrets.AWS_REGION}}

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        shell: bash

        # [2]
      - name: Build with Gradle
        run: ./gradlew build
        shell: bash

        # [3]
      - name: Make zip file
        run: zip -r ./$GITHUB_SHA.zip .
        shell: bash

        # [4]
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: ${{secrets.AWS_REGION}}

        # [5]
      - name: Upload to S3
        run: aws s3 cp --region ap-northeast-2 ./$GITHUB_SHA.zip s3://$S3_BUCKET_NAME/$GITHUB_SHA.zip

        # [6]
      - name: Code Deploy
        run: |
          aws deploy create-deployment \
          --deployment-config-name CodeDeployDefault.AllAtOnce \
          --application-name ${{ env.CODE_DEPLOY_APPLICATION_NAME }} \
          --deployment-group-name ${{ env.CODE_DEPLOY_DEPLOYMENT_GROUP_NAME }} \
          --s3-location bucket=$S3_BUCKET_NAME,bundleType=zip,key=$GITHUB_SHA.zip